name: Build PSP Game

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Compile Project
      run: |
        echo 'CFLAGS += -w -Wno-error -Wno-incompatible-pointer-types' >> Makefile
        echo 'CXXFLAGS += -w -Wno-error -Wno-incompatible-pointer-types' >> Makefile
        make

    - name: Upload EBOOT File
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-PSP-EBOOT
        path: "**/EBOOT.PBP"
