name: Build PSP Game

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Compile Project
      run: |
        make CC="psp-gcc -Wno-incompatible-pointer-types" CXX="psp-g++ -Wno-incompatible-pointer-types"

    - name: Upload EBOOT File
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-PSP-EBOOT
        path: "**/EBOOT.PBP"
